// src/client/01-atoms/svelte/Text.svelte
<script lang="ts">
  import "../styles/Text.css";

  let {label, size, type, color} = $props<{
    label: string;
    size: number;
    type: "primary" | "secondary" | "accent";
    color: string;
  }>();
</script>

<span
  class={`text ${type}`}
  style={`--text-font-size: ${size}rem; --text-color: ${color};`}>
  {label}
</span>

// src/client/01-atoms/react/Text.tsx
import "../styles/Text.css";

type Props = {
  label: string;
  size: number;
  type: "primary" | "secondary" | "accent";
  color: string;
};

export const Text = ({label, size, type, color}: Props) => {
  return (
    <span
      className={`text ${type}`}
      style={
        {
          "--text-font-size": `${size}rem`,
          "--text-color": color,
        } as React.CSSProperties
      }>
      {label}
    </span>
  );
};
