// src/client/01-atoms/react/LinkButton.tsx
type Props = {
  href: string;
  accessibility: string;
  children: React.ReactNode;
};

export const LinkButton = ({href, accessibility, children}: Props) => {
  return (
    <a
      href={href}
      draggable="false"
      aria-label={accessibility}
      onClick={event => {
        if (history.state?.url.includes("/course") && href === "/") {
          event.preventDefault();
          event.stopPropagation();
          history.back();
        }
      }}>
      {children}
    </a>
  );
};

// src/client/01-atoms/svelte/LinkButton.svelte
<script lang="ts">
  import type {SvelteComponent} from "svelte";

  let {href, accessibility, children} = $props<{
    href: string;
    accessibility: string;
    children: () => SvelteComponent;
  }>();
</script>

<a
  {href}
  draggable="false"
  aria-label={accessibility}
  onclick={e => {
    if (history.state?.url.includes("/course") && href === "/") {
      e.preventDefault();
      e.stopPropagation();
      history.back();
    }
  }}>
  {@render children()}
</a>
